import sys


def get_residue_number(ligand_file):
    """
    Extract the residue number of one residue from the original ligand file.
    
    Args:
    - ligand_file (str): Path to the original ligand file.
    
    Returns:
    - int: Residue number of one residue from the original ligand file.
    """
    with open(ligand_file, 'r') as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                residue_number = int(line[22:26].strip())
                return residue_number

def replace_residue_numbers(input_file, output_file, residue_number):
    """
    Replace the residue numbers in the output file generated by ACPYPE with a specified residue number.
    
    Args:
    - input_file (str): Path to the input PDB file generated by ACPYPE.
    - output_file (str): Path to the output PDB file with replaced residue numbers.
    - residue_number (int): Residue number to replace all residue numbers in the ACPYPE output file.
    """
    with open(input_file, 'r') as f:
        lines = f.readlines()

    with open(output_file, 'w') as f:
        for line in lines:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                line = line[:22] + str(residue_number).rjust(4) + line[26:]
            f.write(line)

if __name__ == "__main__":
    ligand_file = sys.argv[1]
    acpype_output_file = sys.argv[2]

    residue_number = get_residue_number(ligand_file)
    replace_residue_numbers(acpype_output_file, acpype_output_file, residue_number)




def get_chain_identifier(ligand_file):
    """
    Extract the chain identifier from the original ligand file.
    
    Args:
    - ligand_file (str): Path to the original ligand file.
    
    Returns:
    - str: Chain identifier.
    """
    with open(ligand_file, 'r') as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                return line[21]


def replace_chain_identifier(input_file, output_file, chain_identifier):
    """
    Replace the chain identifier in the output file generated by ACPYPE.
    
    Args:
    - input_file (str): Path to the input PDB file generated by ACPYPE.
    - output_file (str): Path to the output PDB file with replaced chain identifier.
    - chain_identifier (str): Chain identifier extracted from the original ligand file.
    """
    with open(input_file, 'r') as f:
        lines = f.readlines()

    with open(output_file, 'w') as f:
        for line in lines:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                line = line[:21] + chain_identifier + line[22:]
            f.write(line)

if __name__ == "__main__":
    ligand_file = sys.argv[1]
    acpype_output_file = sys.argv[2]

    chain_identifier = get_chain_identifier(ligand_file)
    replace_chain_identifier(acpype_output_file, acpype_output_file, chain_identifier)

